const FETCH_LOCATIONS_START = 'FETCH_LOCATIONS_START';
const FETCH_LOCATIONS_ERROR = 'FETCH_LOCATIONS_ERROR'
const FETCH_LOCATIONS_SUCCESS = 'FETCH_LOCATIONS_SUCCESS'
const UPDATE_LOCATIONS = 'UPDATE_LOCATIONS'
